version: "3.8"
services:
 web:
  build: .
  volumes:
   - .:/app
  command: go run server.go
  ports:
   - "8080:8080"
  depends_on:
   - db
  restart: always
  network_mode: "host"
 db:
  image: postgres:latest
  container_name: "oms_psql"
  environment:
   - POSTGRES_USER=kspsql
   - POSTGRES_PASSWORD=​pass1111
   - POSTGRES_DB=oms
  ports:
   - "5432:5432"
  restart: always
  network_mode: "host"