version: "3.8"
services:
 web:
  build: .
  volumes:
   - .:/app
  command: go run server.go
  environment:
   - host=localhost
   - port=5432
   - user=kspsql
   - password=pass1111
   - dbname=oms_db
  ports:
   - "8080:8080"
  depends_on:
   - db
  restart: always
  network_mode: "host"
 db:
  image: postgres:latest
  container_name: "oms_psql"
  ports:
   - "5432:5432"
  restart: always
  network_mode: "host"